using System;
using System.Web.UI;
using System.Resources;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("Hewlett-Packard")]
[assembly: AssemblyCopyrightAttribute("Hewlett-Packard. All rights reserved.")]
[assembly: AssemblyTrademarkAttribute("PRISM")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyDescriptionAttribute("PRISM.WEBUI.HyperHelp")]
[assembly: AssemblyVersionAttribute("4.5.00.019")]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyDelaySignAttribute(false)]

